name: Challenge Two

on: push

env:
  ARTIFACT_NAME: "artifactv1"  

jobs:
  upload-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .


