name: Challenge Two

on: push

env:
  ARTIFACT_NAME: "artifactv1"  

jobs:
  upload-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run a script
        run: echo "Upload artifact" > "upload.txt"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${ARTIFACT_NAME}

